[package]
name = "bitoxide"
version = "0.1.0"
author = "F5XS"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true

[dependencies]
clap = { version = "4.3", features = ["derive"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
